#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill '/home/skaplan/wallpapers/test_wallpaper.jpg' &
wal -i $HOME/wallpapers/test_wallpaper.jpg &
. "${HOME}/.cache/wal/colors.sh" 
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback-color "$color1"
bspc config presel_feedback_color "$color1"
bspc config focus_follows_pointer true
bspc config border_width 2
bspc config window_gap 25
Bspc config split_ration 0.52
bspc config boderless_monocle true
bspc config gapless_monocle true

$HOME/.config/polybar/launch.sh

picom --config ~/.config/picom/picom.conf &
